kind: Pod
apiVersion: v1
metadata: 
  name: annotationpod
  annotations:
    Email: hamadali@gmail.com
    Age: 44 years
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80     
