kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployexample
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deploy-app
  template:
    metadata:
      name: deploy-pod
      labels:        
        app: deploy-app
    spec:
      containers:
      - name: container1
        image: aamirpinger/helloworld
        imagePullPolicy: IfNotPresent
