kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-rolling-update
spec:
   replicas: 2
   selector:
     matchLabels:
       deployment: rollingupdate
   template:
     metadata:
       name: deployrolling-pod 
       labels:
         deployment: rollingupdate
     spec:
       containers:
       - name: nginx
         image: aamirpinger/helloworld
         imagePullPolicy: IfNotPresent
   strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 0
       maxSurge: 1 
       
