kind: Pod
apiVersion: v1
metadata:
  name: wrong-pod

spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command: 
        - ls
