apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: whalesay
        image: docker/whalesay
        command: ["cowsay", "This is Kubernetes job"]
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 60
