kind: Pod
apiVersion: v1
metadata:
  name: labelpod1
  labels:
    type: backend
    env: production
spec:
  containers:
  - image: aamirpinger/helloworld:latest
    name: container1
    ports:
    - containerPort: 80    
