apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: dryrunpod
  name: dryrunpod
spec:
  containers:
  - image: nginx
    name: dryrunpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

