kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: repiasad
  namespace: development
spec:
  replicas: 4     
  selector:
    matchLabels: 
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: repiasad
          image: nginx
          ports: 
          - containerPort: 80
