apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: aamirpinger/helloworld
        ports:
        - containerPort: 80
