kind: Pod
apiVersion: v1
metadata:
  name: myapp-vol
spec:
  volumes:
    - name: my-volume
      emptyDir: {}
  containers:
  - image: aamirpinger/helloworld
    name: container1
    ports:
    - containerPort: 80     
    volumeMounts:
    - name: my-volume
      mountPath: /data
    imagePullPolicy: IfNotPresent
  - image: aamirpinger/node-js-app
    name: container2
    ports:
    - containerPort: 8080     
    volumeMounts:
    - name: my-volume
      mountPath: /abc
    imagePullPolicy: IfNotPresent
  - image: hammadd2/python
    name: container3
    ports:
    - containerPort: 4000    
    volumeMounts:
    - name: my-volume
      mountPath: /bbc
    imagePullPolicy: IfNotPresent
      
